prime = {
        "A":3,
        "B":5,
        "C":7,
        "D":11,
        "E":13,
        "F":17,
        "G":19,
        "H":23,
        "I":29,
        "J":31,
        "K":37,
        "L":41,
        "M":43,
        "N":47,
        "O":53,
        "P":59,
        "Q":61,
        "R":67,
        "S":71,
        "T":73,
        "U":79,
        "V":83,
        "W":89,
        "X":97,
        "Y":101,
        "Z":103
        }

print(prime["C"]*prime["J"])
print(prime["J"]*prime["Q"])
print(prime["Q"]*prime["U"])
print(prime["U"]*prime["I"])
